services:

  dan-ms-usuarios:
   container_name: dan-ms-usuarios
<<<<<<< HEAD
   image: dan/ms-usuarios:0.0.1-SNAPSHOT
   restart: always  
=======
   image: criquelme05/dan-ms-usuarios:latest     
>>>>>>> 636200bcb2e653c6ad53f033c2de56d85234680c
   ports:
    - "9000:8080"
   environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "SERVER_PORT=8080"
    - "SPRING_APPLICATION_NAME=usuario"
    - "SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/dan?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
   networks:
    - app

  dan-ms-material:
   container_name: dan-ms-material
<<<<<<< HEAD
   image: dan/ms-material:0.0.1-SNAPSHOT 
   restart: always   
=======
   image: criquelme05/dan-ms-material:latest     
>>>>>>> 636200bcb2e653c6ad53f033c2de56d85234680c
   ports:
    - "9001:8080"
   environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "SERVER_PORT=8080"
    - "SPRING_APPLICATION_NAME=material"
    - "SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/ms_material?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    - "spring.artemis.host=artemis"
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
   networks:
    - app

  dan-ms-pedidos:
   container_name: dan-ms-pedidos
<<<<<<< HEAD
   image: dan/ms-pedidos:0.0.1-SNAPSHOT
   restart: always
=======
   image: criquelme05/dan-ms-pedidos:latest
>>>>>>> 636200bcb2e653c6ad53f033c2de56d85234680c
   ports: 
    - "9002:8080"
   environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "SERVER_PORT=8080"
    - "SPRING_APPLICATION_NAME=pedido"
    - "SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/ms_pedidos?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    - "spring.artemis.host=artemis"
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
   networks:
    - app

  dan-ms-cuenta:
   container_name: dan-ms-cuenta
<<<<<<< HEAD
   image: dan/ms-cuenta:0.0.1-SNAPSHOT
   restart: always  
=======
   image: criquelme05/dan-ms-cuenta:latest     
>>>>>>> 636200bcb2e653c6ad53f033c2de56d85234680c
   ports:
    - "9003:8080"
   environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "SERVER_PORT=8080"
    - "SPRING_APPLICATION_NAME=cuenta"
    - "SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/dan?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
   networks:
    - app

  dan-ms-blog:
   container_name: dan-ms-blog
   image: dan/ms-blog:0.0.1-SNAPSHOT
   restart: always
   ports: 
    - "9005:8080"
   environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "SERVER_PORT=8080"
    - "SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/ms_blog?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
   networks:
    - app
   

  zuul-server:
    container_name: zuul-server
    image: criquelme05/dan-zuul-server:latest
    ports:
      - "9100:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=8080"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
      - "zuul_routes_pedido_path=/pedido/**"
      - "zuul_routes_pedido_url=http://dan-ms-pedidos:8080"      
      - "zuul_routes_material_path=/material/**"
      - "zuul_routes_material_url=http://dan-ms-material:8080"
      - "zuul_routes_usuario_path=/usuario/**"
      - "zuul_routes_usuario_url=http://dan-ms-usuarios:8080"
      - "zuul_routes_cuenta_path=/cuenta/**"
      - "zuul_routes_cuenta_url=http://dan-ms-cuenta:8080"
      - "zuul_routes_blog_path=/blog/**"
      - "zuul_routes_blog_url=http://dan-ms-blog:8080"
      
    networks:
      - app

  eureka-server: 
    container_name: eureka-server
    image: criquelme05/dan-eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - app

  db-mysql:
   container_name: db-mysql
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
   volumes:
    - ./dan-ms-app.sql:/docker-entrypoint-initdb.d/init.sql
    - ./mysql-data:/var/lib/mysql
   ports:
    - "3306:3306"
   networks:
    - infra
    - app  

  cloud-gateway:
    container_name: cloud-gateway
    image: criquelme05/dan-cloud-gateway:latest
    ports:
      - "9200:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=8080"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"      
    networks:
      - app

  db-postgres:
    container_name: db-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dan
    networks:
      - infra
      - app
    volumes:
      - ./pg/data:/var/lib/postgresql/data
          
  adminer:
   container_name: adminer
   image: adminer
   restart: always
   ports:
    - 6001:8080
   networks:
    - infra
  
  artemis:
   container_name: artemis
   build: ./artemis
   image: dan-artemis
   restart: always
   ports:
     - "61616:61616" 
     - "8161:8161"
     - "5445:5445"
     - "5672:5672"
     - "1883:1883" 
     - "61613:61613"
   networks:
     - app
     - infra   

  prometheus: 
    container_name: prometheus
    image: prom/prometheus 
    restart: always 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    ports: 
      - 9090:9090
    networks: 
      - infra
      - app

  grafana: 
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports: 
      - 3000:3000
    networks: 
      - infra
  
networks:
    infra:
      driver: bridge
    app:
      driver: bridge   
    
    



 
